// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/appointment/book": {
            "post": {
                "tags": [
                    "Appointment Handlers"
                ],
                "summary": "Patient books an appointment",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AppointmentRequest"
                        }
                    },
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.AppointmentResponse"
                        }
                    }
                }
            }
        },
        "/appointment/doc-all": {
            "get": {
                "tags": [
                    "Appointment Handlers"
                ],
                "summary": "Doctor gets all his appointments",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.AppointmentResponse"
                            }
                        }
                    }
                }
            }
        },
        "/appointment/pat-all/{patientid}": {
            "get": {
                "tags": [
                    "Appointment Handlers"
                ],
                "summary": "Patient gets all his appointments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Patient UUID",
                        "name": "patientid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.AppointmentResponse"
                            }
                        }
                    }
                }
            }
        },
        "/appointment/{appointmentid}": {
            "get": {
                "tags": [
                    "Appointment Handlers"
                ],
                "summary": "Get an appointment, Doctor or Patient views an appointment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Apointment UUID",
                        "name": "appointmentid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.AppointmentResponse"
                        }
                    }
                }
            }
        },
        "/delete-all/{patientid}": {
            "delete": {
                "tags": [
                    "Appointment Handlers"
                ],
                "summary": "Delete all appointment by a Patient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Patient UUID",
                        "name": "patientid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "All appointments deleted successfully"
                    }
                }
            }
        },
        "/delete/{appointmentid}": {
            "delete": {
                "tags": [
                    "Appointment Handlers"
                ],
                "summary": "Delete an appointment by a Doctor or Patient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Apointment UUID",
                        "name": "appointmentid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Appointment deleted successfully"
                    }
                }
            }
        },
        "/doctors/all": {
            "get": {
                "tags": [
                    "Appointment Handlers"
                ],
                "summary": "Patient gets list of doctors",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.DoctorResp"
                            }
                        }
                    }
                }
            }
        },
        "/signin/doctor": {
            "post": {
                "tags": [
                    "Authentication Handlers"
                ],
                "summary": "Login as a Doctor",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    }
                }
            }
        },
        "/signin/patient": {
            "post": {
                "tags": [
                    "Authentication Handlers"
                ],
                "summary": "Login as a Patient",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    }
                }
            }
        },
        "/signup/doctor": {
            "post": {
                "tags": [
                    "Authentication Handlers"
                ],
                "summary": "Register as a Doctor",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.SignUpResponse"
                        }
                    }
                }
            }
        },
        "/signup/patient": {
            "post": {
                "tags": [
                    "Authentication Handlers"
                ],
                "summary": "Register as a Patient",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.SignUpResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AppointmentRequest": {
            "type": "object",
            "properties": {
                "appointment_date": {
                    "type": "string"
                },
                "appointment_details": {
                    "type": "string"
                },
                "appointment_time": {
                    "type": "string"
                },
                "doctor_email": {
                    "type": "string"
                }
            }
        },
        "models.AppointmentResponse": {
            "type": "object",
            "properties": {
                "appointment_date": {
                    "type": "string"
                },
                "appointment_details": {
                    "type": "string"
                },
                "appointment_time": {
                    "type": "string"
                },
                "appointment_uuid": {
                    "type": "string"
                },
                "doctor_email": {
                    "type": "string"
                },
                "patient_email": {
                    "type": "string"
                },
                "patient_name": {
                    "type": "string"
                },
                "patient_uuid": {
                    "type": "string"
                }
            }
        },
        "models.DoctorResp": {
            "type": "object",
            "properties": {
                "doctor_email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user_uuid": {
                    "type": "string"
                }
            }
        },
        "models.SignUpRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.SignUpResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user_uuid": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Group 14 Hospital Information System",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
