definitions:
  models.Appointment:
    properties:
      appointmentDate:
        type: string
      appointmentDetails:
        type: string
      appointmentID:
        type: integer
      appointmentTime:
        type: string
      appointmentUUID:
        type: string
      createdAt:
        type: string
      doctorID:
        type: integer
      doctorUUID:
        type: string
      patientID:
        type: integer
      patientUUID:
        type: string
    type: object
  models.AppointmentRequest:
    properties:
      appointment_date:
        type: string
      appointment_details:
        type: string
      appointment_time:
        type: string
      doctor_email:
        type: string
    type: object
  models.AppointmentResponse:
    properties:
      appointment_date:
        type: string
      appointment_details:
        type: string
      appointment_time:
        type: string
      appointment_uuid:
        type: string
      doctor_email:
        type: string
      patient_email:
        type: string
      patient_name:
        type: string
      patient_uuid:
        type: string
    type: object
  models.DoctorResp:
    properties:
      doctor_email:
        type: string
      doctor_uuid:
        type: string
      first_name:
        type: string
      last_name:
        type: string
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.LoginResponse:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      role:
        type: string
      token:
        type: string
      user_uuid:
        type: string
    type: object
  models.SignUpRequest:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
    type: object
  models.SignUpResponse:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      role:
        type: string
      token:
        type: string
      user_uuid:
        type: string
    type: object
info:
  contact: {}
  title: Group 14 Hospital Information System
paths:
  /appointment/{appointmentid}:
    get:
      parameters:
      - description: Apointment UUID
        in: path
        name: appointmentid
        required: true
        type: string
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.AppointmentResponse'
      summary: Get an appointment, Doctor or Patient views an appointment
      tags:
      - Appointment Handlers
    put:
      parameters:
      - description: Apointment UUID
        in: path
        name: appointmentid
        required: true
        type: string
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Appointment'
      summary: Update an appointment
      tags:
      - Appointment Handlers
  /appointment/book:
    post:
      parameters:
      - description: payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.AppointmentRequest'
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.AppointmentResponse'
      summary: Patient books an appointment
      tags:
      - Appointment Handlers
  /appointment/doc-all:
    get:
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.AppointmentResponse'
            type: array
      summary: Doctor gets all his appointments
      tags:
      - Appointment Handlers
  /appointment/pat-all/{patientid}:
    get:
      parameters:
      - description: Patient UUID
        in: path
        name: patientid
        required: true
        type: string
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.AppointmentResponse'
            type: array
      summary: Patient gets all his appointments
      tags:
      - Appointment Handlers
  /delete-all/{patientid}:
    delete:
      parameters:
      - description: Patient UUID
        in: path
        name: patientid
        required: true
        type: string
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: All appointments deleted successfully
      summary: Delete all appointment by a Patient
      tags:
      - Appointment Handlers
  /delete/{appointmentid}:
    delete:
      parameters:
      - description: Apointment UUID
        in: path
        name: appointmentid
        required: true
        type: string
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: Appointment deleted successfully
      summary: Delete an appointment by a Doctor or Patient
      tags:
      - Appointment Handlers
  /doctors/{doctorid}:
    get:
      parameters:
      - description: Doctor UUID
        in: path
        name: doctorid
        required: true
        type: string
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DoctorResp'
      summary: Get a particular doctor details
      tags:
      - Appointment Handlers
  /doctors/all:
    get:
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.DoctorResp'
            type: array
      summary: Patient gets list of doctors
      tags:
      - Appointment Handlers
  /signin/doctor:
    post:
      parameters:
      - description: payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.LoginResponse'
      summary: Login as a Doctor
      tags:
      - Authentication Handlers
  /signin/patient:
    post:
      parameters:
      - description: payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.LoginResponse'
      summary: Login as a Patient
      tags:
      - Authentication Handlers
  /signup/doctor:
    post:
      parameters:
      - description: payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.SignUpRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.SignUpResponse'
      summary: Register as a Doctor
      tags:
      - Authentication Handlers
  /signup/patient:
    post:
      parameters:
      - description: payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.SignUpRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.SignUpResponse'
      summary: Register as a Patient
      tags:
      - Authentication Handlers
swagger: "2.0"
